spring.application.name=pbl5

spring.datasource.url=jdbc:postgresql://localhost:5432/PBL5
spring.datasource.username=postgres
spring.datasource.password=123456

jwt.secret=5W/gsQQnANpfq28MssMTclP3MUJ6blNTAMEvaKn/mq0=
jwt.expiration=86400000

server.address=0.0.0.0
server.port=8088

app.base-url=http://localhost:8088

ai.http.base-url=https://utdaica-pbl5-fruit-classifier.hf.space
ai.http.api-key=
ai.http.connect-timeout-ms=5000
ai.http.read-timeout-ms=60000

storage.type=local
